# Generated by Django 3.0.2 on 2020-01-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='fileShow',
            new_name='filePath',
        ),
    ]
